// src/components/common/ToTop.svelte
<script>
  import { fade } from 'svelte/transition'
  import { easeInOut } from '@/utils'

  export let offset = 600
  export let transitionOptions = { duration: 250, easing: easeInOut }

  let scrollTop = 0

  $: active = scrollTop > offset

  function onScroll() {
    scrollTop = window.pageYOffset
  }

  function scrollToTop() {
    const currentScroll = window.pageYOffset
    if (currentScroll > 0) {
      requestAnimationFrame(scrollToTop)
      window.scrollTo(0, Math.floor(currentScroll - currentScroll / 5))
    }
  }
</script>

<svelte:window on:scroll={onScroll} />

{#if active}
  <button
    class="to-top"
    type="button"
    aria-label="Scroll to top"
    {...$$restProps}
    transition:fade={transitionOptions}
    on:click={scrollToTop}
  >
    <slot>
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <path
          d="M7.41,15.41L12,10.83L16.59,15.41L18,14L12,8L6,14L7.41,15.41Z"
        />
      </svg>
    </slot>
  </button>
{/if}

<style lang="postcss" global>
  .to-top {
    width: 60px;
    height: 60px;
    background-color: var(--theme-color);
    border-radius: 50%;
    position: fixed;
    border: none;
    right: 40px;
    bottom: 40px;
    z-index: var(--z-index-fixed);
    transition: var(--transition);
    transition-property: background-color;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #ffffff;
    font-size: 24px;
    -webkit-tap-highlight-color: transparent;

    @mixin down md {
      width: 55px;
      height: 55px;
      right: 20px;
      bottom: 20px;
    }

    svg {
      display: block;
      height: 1em;
      fill: currentColor;
    }
  }
</style>

// src/components/solid/ToTop.jsx
import {
  onMount,
  onCleanup,
  createSignal,
  createMemo,
  splitProps
} from 'solid-js'

export default function ToTop(props) {
  const [, rest] = splitProps(props, ['offset', 'children'])
  const [scrollTop, setScrollTop] = createSignal(0)
  const active = createMemo(() => scrollTop() > (props.offset || 600))

  function scrollToTop() {
    const currentScroll = window.pageYOffset
    if (currentScroll > 0) {
      requestAnimationFrame(scrollToTop)
      window.scrollTo(0, Math.floor(currentScroll - currentScroll / 5))
    }
  }

  onMount(() => {
    function onScroll() {
      setScrollTop(window.pageYOffset)
    }
    window.addEventListener('scroll', onScroll)
    onCleanup(() => window.removeEventListener('scroll', onScroll))
  })

  return (
    <button
      class="pointer-events-none fixed right-5 bottom-5 z-fixed flex h-14 w-14 items-center justify-center rounded-full bg-indigo-500 text-white opacity-0 transition duration-200 hover:bg-indigo-400 focus:outline-none focus-visible:ring focus-visible:ring-indigo-500/50 focus-visible:ring-offset-2 active:bg-indigo-600 md:right-10 md:bottom-10"
      classList={{ 'pointer-events-auto opacity-100': active() }}
      type="button"
      aria-label="Scroll to top"
      {...rest}
      onClick={scrollToTop}
    >
      {props.children || (
        <svg class="h-6 fill-current" viewBox="0 0 24 24" aria-hidden="true">
          <path d="M7.41,15.41L12,10.83L16.59,15.41L18,14L12,8L6,14L7.41,15.41Z" />
        </svg>
      )}
    </button>
  )
}
