// src/components/solid/Button.jsx
import { splitProps, mergeProps } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import Spinner from './Spinner.jsx'

export default function Button(props) {
  props = mergeProps({ as: 'button', size: 'md' }, props)
  const [, rest] = splitProps(props, [
    'class',
    'classList',
    'as',
    'variant',
    'size',
    'disabled',
    'loading',
    'spinner',
    'children',
    'href'
  ])

  return (
    <Dynamic
      component={props.as}
      class="relative inline-flex cursor-pointer items-center justify-center rounded text-center align-middle transition focus:outline-none"
      classList={{
        [props.class]: Boolean(props.class),
        ...props.classList,
        'bg-indigo-500 text-white hover:bg-indigo-400 focus-visible:ring focus-visible:ring-indigo-500/50 focus-visible:ring-offset-2 active:bg-indigo-600':
          props.variant === 'primary' && !props.disabled,
        'text-slate-500 bg-slate-300 pointer-events-none': props.disabled,
        'pointer-events-none': props.loading,
        'min-h-10 py-1 px-5 text-base [--spinner-size:22px]':
          props.size === 'md'
      }}
      href={props.disabled || props.loading ? null : props.href}
      disabled={props.disabled || props.loading}
      {...rest}
    >
      {props.loading ? (
        <>
          <span class="invisible contents">{props.children}</span>
          <span class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
            {props.spinner || <Spinner />}
          </span>
        </>
      ) : (
        props.children
      )}
    </Dynamic>
  )
}

// src/components/common/Button.svelte
<script>
  import Spinner from './Spinner.svelte'
  import { actionsAction } from '@/actions'

  let className = ''
  export { className as class }
  export let size = ''
  export let variant = ''
  export let loading = false
  export let type = 'button'
  export let href = ''
  export let use = null
  export let disabled = false
  export let el = undefined

  $: classes = [
    'button',
    variant && `button_${variant}`,
    size && `button_${size}`,
    disabled && 'button_disabled',
    loading && 'button_loading',
    className
  ]
    .filter(Boolean)
    .join(' ')
</script>

{#if href}
  <a
    class={classes}
    href={disabled ? undefined : href}
    {...$$restProps}
    bind:this={el}
    use:actionsAction={use}
    on:click
  >
    <span class="button__content">
      <slot />
    </span>
    {#if loading}
      <Spinner size={23} width={2} class="button__spinner" />
    {/if}
  </a>
{:else}
  <button
    class={classes}
    {type}
    {disabled}
    {...$$restProps}
    bind:this={el}
    use:actionsAction={use}
    on:click
  >
    <span class="button__content">
      <slot />
    </span>
    {#if loading}
      <Spinner size={23} width={2} class="button__spinner" />
    {/if}
  </button>
{/if}

<style lang="postcss" global>
  .button {
    cursor: pointer;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    vertical-align: middle;
    text-align: center;
    color: var(--body-color);
    user-select: none;
    background-color: transparent;
    border: 1px solid transparent;
    line-height: var(--line-height);
    font-size: 16px;
    padding: 6px 12px;
    border-radius: 4px;
    transition: 0.25s var(--fast-out-slow-in);
    transition-property: color, background-color, border-color, box-shadow;
    max-width: 100%;
    min-width: 48px;
    flex: 0 0 auto;
    position: relative;

    &:hover {
      text-decoration: none;
    }

    &:focus-visible {
      z-index: 1;
    }

    &_disabled {
      pointer-events: none;
      opacity: 0.65;
    }

    &_primary {
      color: #ffffff;
      background-color: $color-primary;
      border-color: $color-primary;

      &:hover {
        background-color: lighten($color-primary, 0.05);
        border-color: lighten($color-primary, 0.05);
      }

      &:active {
        background-color: darken($color-primary, 0.05);
        border-color: darken($color-primary, 0.05);
      }
    }

    &_small {
      padding: 4px 8px;
      font-size: 14px;
      border-radius: 3px;
    }

    &_large {
      padding: 8px 16px;
      font-size: 20px;
      border-radius: 5px;
    }

    &_loading {
      pointer-events: none;
      transition: none;
    }

    &__content {
      align-items: center;
      display: flex;
      flex: 1 0 auto;
      justify-content: inherit;
    }

    &_loading &__content {
      opacity: 0;
    }

    &__spinner.spinner {
      display: flex;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }
  }
</style>
